### ISSUE TITLE
Filter vs ActionCreator vs HttpRequestHandler

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#134]
Apart from the `@Secure` annotation and the `Secure` function (which somehow are specific to the Play pac4j implementation), we currently have the `SecurityFilter` to provide a general interception mechanism.
Though, there is a limitation: "the request body is not available" (https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/Xdk4igV9kNE).

And we have other potential mechanisms: `ActionCreator` and `HttpRequestHandler` (https://www.playframework.com/documentation/2.5.x/JavaActionCreator).

Which one(s) should we really propose?

CC: @entropicdrifter @andriykuba @hugovalk

**Comment by petenattress** [comment]
Hi - I initially raised this on the Google group.

You are correct that I will need to manually define which URLs are protected if I'm using my custom SecureAction solution. The code in my ActionCreator looks a bit like this:

```java
  @Override
  public Action createAction(Http.Request request, Method actionMethod) {

    if (request.uri().startsWith("/apply")) { //More patterns will be defined here
      //Ensure a new action instance is created for each request
      return new FixedSecureAction();
    }
    else {
      //No protection - simple delegating action
      return new Action.Simple() {
        @Override
        public CompletionStage<Result> call(Http.Context ctx) {
          return delegate.call(ctx);
        }
      };
    }
  }
```

Obviously it would be much more preferable if the configuration markup as used for filters could be reused here somehow. I only have one client and one authorizer but my current solution would be very messy for anyone with a more complex setup.

I think it would be much neater if I could ask Pac4j for an `Action` in my `createAction` method which encapsulated all the pattern matching logic which is already available in the filter mechanism. The only caveat would be that it would need to cater for chaining or decorating `Action`s, in case I have another `Action` I wish to apply to my requests.

I have not used the `HttpRequestHandler`, but looking at the API it appears that only the `RequestHeader` is available to its methods. If this is the case it indicates that the HTTP request body will not be available within it, which would not solve the problem we're talking about.

**Comment by leleuj** [comment]
OK. So the `HttpRequestHandler` does not provide any value, compared to our existing `SecurityFilter`.

What are the pros and cons of the `SecureActionCreator` vs the `SecurityFilter`?

@petenattress : are you interested in contributing a `SecureActionCreator` with a patterns mechanism shared with the `SecurityFilter`?

**Comment by petenattress** [comment]
As far as I can tell at the moment, the only benefit of a `SecureActionCreator` over `SecurityFilter` is if your authentication logic (i.e. the `Authorizer`) requires access to the parsed request body. In my case this is a posted form parameter, but anyone who needs to inspect the request body (e.g. to read a field from a JSON object) may find it useful. It's also only useful if you have a large amount of controllers you wish to subject to the same authentication using URL pattern matching; otherwise you might as well just use the `@Secure` annotation.

Disadvantages: as far as I can tell Play only allows you to have one global `ActionCreator`. The `Action` created from a `SecureActionCreator` would need to decorate another `ActionCreator`'s `Action`, if the developer required it to. I'm not sure how straightforward this would be.

I don't mind having a go at prototyping what the `SecureActionCreator` would look like, if you agree it would be a valuable addition to the library. Otherwise I am happy to continue using my "hack" solution as I appreciate my use case may be something of an edge case.

**Comment by entropicdrifter** [comment]
In my most recent project, I found it most useful to simply extend the Controller class with an otherwise blank class that has the `@Secure` annotation applied at the class level. That way only classes that need both unsecured and secured methods require the `@Secure` annotation at the individual method level.

Simple workarounds aside, I have noted a related issue with Direct Authentication methods not saving the user profile if the authentication is done inside the `SecurityFilter` class. Since the `DefaultSecurityLogic` doesn't save the Profile to the session for Direct Authentication methods in order to preserve statelessness, it falls back on only saving the Profile to the Context, which is not passed through to the Controllers after the Filter. I have yet to find an elegant solution to this other than the workaround stated above, which relies on calling the `@Secure` annotation. 

I considered at one point attempting to put the user's Profile information into the request headers somehow, but it seems Play was intentionally designed to make tampering with the underlying header hard if not borderline impossible to do.

Thus, as it stands, if a developer wants to use either a Direct Authentication scheme where the Profile object is used inside one or more controllers or any scheme that relies on the request body, they need to apply the `@Secure` annotation at either the method or class level.

**Comment by leleuj** [comment]
Thanks for your feedbacks.

@entropicdrifter raises two good points:

1) using the `@Secure` annotation at the Controller level makes things easier, but it only works for Java, isn't it? @petenattress would it be sufficient for you?

2) Yes, the Profile is saved into the Context. In fact, you can change that with the `setSaveProfileInSession` method on the logic.
The idea is to make the Profile available only for this HTTP request: I'm open to suggestion if you have a better implementation which works with the `SecurityFilter`.

Currently, my feeling is that we have already many options and we shouldn't add a `SecureActionCreator`.

**Comment by hugovalk** [comment]
Hi all,

Please consider that the Play framework has been designed with reactive design principles in mind. Typically this means that body parsing is deferred to the latest possible moment. 
Also the Play framework supports Reactive Streams. 
This means that large requests (like file uploads for example) don't have to be parsed when for example authentication fails. 

As a general design principle it is therefore not recommended to store authentication credentials (such as a key or token) in the request body. One would typically use the Authorization header, which should be available. The request body will then not be streamed and parsed when authorization fails. 

I can imagine that certain legacy situations require you to use the body, however, this should in my opinion be discouraged and therefore not supported in the play-pac4j library.

Kind regards, Hugo

**Comment by millross** [comment]
Regarding Hugo's statement, the same applies to vert.x for very similar reasons.

**Comment by leleuj** [comment]
Thank you all for your feedbacks.

It seems we should not go further on the `SecureActionCreator` which does not prevent @petenattress from implementing his custom solution for his needs.
