### ISSUE TITLE
Context args are lost using SecurityFilter pac4j-play 2.4.0

### ISSUE THREAD

**Issue by richard77** [pac4j/play-pac4j#145]
When using a ```DirectClientV2``` the ```UserProfile``` should be stored in the context args. 

Using the ```SecurityFilter``` it creates a ```PlayWebContext``` using the requestHeader. Any data set on this object is lost when accessing it from a controller or template.
Resulting in not being able to retrieve the ```UserProfile``` using the ```ProfileManager```.

Using an ```@Secure``` Annotation on the controller method instead, gives us the correct context with arguments still set.

**Comment by leleuj** [comment]
There is a bunch of issues with the `SecurityFilter` (https://github.com/pac4j/play-pac4j/issues/144 and https://github.com/pac4j/play-pac4j/issues/142 also) which mainly comes from the way the `PlayWebContext`.

I'm investigating, but any help will be appreciated.

**Comment by richard77** [comment]
I already assumed it might be related, but the main difference between this and #144 is that this also occurs in 2.4.0
I'll try to see what happens in a debugger session. Although I must say I'm not so into Scala.

**Comment by leleuj** [comment]
Me neither. Maybe we'll end up rewriting the filter in Java ;-)

**Comment by richard77** [comment]
Hi,

Quick evaluation: After using the securityFilter Play only keeps the RequestHeader object and creates a new HttpContext using the requestHeader tags. Setting a value on this instead the context.args retains the value for the controller action call.

**Comment by leleuj** [comment]
I'm not sure to follow you: do you have a code example? Or (better) can you submit a PR?

I easily configured the filter in a Play Scala app, but encounter a strange error in a Play Java app (`Error injecting constructor, java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lplay.mvc.EssentialFilter;`).

Here is my simple `Filters` though:

```java
public class Filters extends DefaultHttpFilters {
    @Inject
    public Filters(SecurityFilter securityFilter) {
        super(securityFilter);
    }
}
```

How do you configure the `SecurityFilter` in your Java app?

**Comment by richard77** [comment]
I did not alter any code yet. I've configured my clients normally with use of the securityFilter.

I was running a debugging session in my IDE and put a test value in the RequestHeader tags instead of the map. Those values were available to me later on in the Controller method. The args hashMap (the one with the profiles set) was lost.

My configuration has an IPClient with a IpRegexAuthenticator in place
```final IpClient ipClient = new IpClient(new IpRegexpAuthenticator("127.0.0.1"));```

Let me try to explain what happens:

1. SecurityFilter:78 creates a Http.Context instance based on the RequestHeader
2. With this context the SecureAction is called (SecurityFilter:81)
3. DefaultSecurityLogic:120 calls profileManager.save(false,....) for a DirectClient which puts the profile in the request.args map. The underlying httpHeader.tags is not updated.
4. When successfully authenticated the DefaultSecurityLogic:139 calls the securityGrantedAccessAdapter where in my opinion stuff breaks...

Using the securityFilter approach we have no delegate in SecureAction:90 to SecureAction:94. This results in play returning and eventually creating a new HttpContext using the RequestBody. (JavaHelpers.scala:96  ``` def createJavaContext(req: Request[RequestBody]): JContext = {...}```)

Using the ```@Secure``` annotation we do have the delegate and the already created HttpContext is used and thus the ```args``` are still available to us. 

Possible solutions are to either ensure there is a delegate Action when using the securityFilter (not sure if this is possible) or put the profile information in the RequestHeader.tags somehow to keep the profile.

Hope this helps. 
/Richard

**Comment by richard77** [comment]
Short update:  
As I understand Filters now, play will never have the delegate Action available in the ```securityGrantedAccessAdapter```.
The RequestHeader.tags is a HashMap<String,String> object so keeping a reference to the Profile instance is not possible too. 
I've looked at the Http.Flash which is copied into the Http.Context, but that also is a HashMap<String,String> underneath. So keeping pointers alive is going to be difficult how I see it now.

**Comment by leleuj** [comment]
I can reproduce the issue (in Java for now), but indeed, things are fairly complicated. I have different `Http.Context` so the args are lost.
Returning `null` when there is not delegate is certainly the source of evil.

**Comment by leleuj** [comment]
The main issue is that we don't have any request attributes in Play.

I've been digging a little more and now I see your point with the `args` of the `Context`, built from the `tags` of the `request(header)`. One is a map of strings, the other one a map of objects. So we could copy back the `args`  into the `tags`, but we would need to serialize them because `tags` are only strings.

Another option is maybe to return something other than `null` in the `SecureAction` when there is no `delegate`, but I haven't found out yet what it could b.

Or we could use the session for the HTTP request attributes as well. Straightforward, even if it's not exactly the expected *pac4j* behaviour.
Pushing a little further this reasoning, I'm wondering if we could use the session but with a special prefix including the request id (and a specific timeout), to attach the information only to the corresponding HTTP request.

What do you think?

**Comment by leleuj** [comment]
In fact, an additional unique app identifier will be also necessary to avoid any mix between requests of various applications sharing the same cache.

**Comment by leleuj** [comment]
I found the way to declare the filter in Java (and fixed the documentation BTW):

```java
package filters;

import org.pac4j.play.filters.SecurityFilter;
import play.http.HttpFilters;
import play.mvc.EssentialFilter;

import javax.inject.Inject;

public class Filters implements HttpFilters {

    private final SecurityFilter securityFilter;

    @Inject
    public Filters(SecurityFilter securityFilter) {
        this.securityFilter = securityFilter;
    }

    @Override
    public EssentialFilter[] filters() {
        return new EssentialFilter[] { securityFilter.asJava() };
    }
}
```

**Comment by richard77** [comment]
Play has a key for this ```http.session.cookieName``` to ensure uniqueness of session values. if that's what you mean.

More in line with the philosophy of Play we could introduce a FlashStore similar to the SessionStore. Flash is automatically request scoped and would not pollute the sessionStore.
That said, putting the values in the SessionStore is the best solution with the minimum effort.

Let me know what suits you the best.

**Comment by leleuj** [comment]
But the FlashStore only accepts strings, doesn't it? I'll take a look.

**Comment by leleuj** [comment]
I just submitted https://github.com/pac4j/play-pac4j/pull/148: I now use the flash scope for the HTTP attributes (by serializing them) and the tags as a hack to pass the profiles between the Java context and the `SecurityFilter`.

It works and it's proper enough. IMHO.

**Comment by leleuj** [comment]
For 2.5.x as well: https://github.com/pac4j/play-pac4j/pull/149

**Comment by leleuj** [comment]
I'm not sure we really need to fix that for play-pac4j 2.4.x as the version to use for Play 2.5 is play-pac4j 2.5.

**Comment by leleuj** [comment]
@richard77 : merging the fixes. Would you mind confirming the patch and closing the issue?

**Comment by richard77** [comment]
I'll do that. Thanks!
Op di 18 okt. 2016 om 10:18 schreef LELEU Jérôme <notifications@github.com>

**Comment by KarelCemus** [comment]
Hi, I just updated from 2.5.0 to 2.5.1 and it suddenly flooded my logs with `ClassNotFoundException`. I've already spent couple hours investigating what went wrong and it turned out that it is this PR. More specifically, the reimplementation of `PlayWebContext#getRequestAttribute`.  Inspecting the change I figured out kinda major changes in the implementation. These should not be published as a bugfix update but the minor version change. However, I'll look at it more deeply and let you know what is wrong.

Note: I'm using pac4j with Scala

**Comment by KarelCemus** [comment]
OK, so there are couple issues I found out:

- In comments above, you assume flash scope equals request scope which is not. It is a bit longer and intended to pass value among 2 requests where the first one should be Redirect. In consequence, there are these warnings in logs:
```
13:48:18 [warn] play You are using status code '200' with flashing, which should only be used with a redirect status!
```
Using flash scope for this is pretty nasty solution
- Second, since 2.5.1 you invoke `JavaSerializationHelper`, which was not used before and thus it is not tested and migrated to in production, 2.5.0 version does not invoke it (or at least I did not find it)

- Third, since bugfix release you introduce `trustedPackages` in `JavaSerializationHelper` and reject untrusted classes. Personally, I see that as a bad practice because it requires migration, i.e., not bugfixing release

- When I fixed the third issue, I ended up (again) with the `ClassNotFoundException`, but this time directly from the ObjectInputStream. I don't know what classloader it uses but it is probably the wrong one. There is the relevant part of the exception call stack:
```
java.lang.ClassNotFoundException: app.social.user.UserProfile
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at org.pac4j.core.util.JavaSerializationHelper$RestrictedObjectInputStream.resolveClass(JavaSerializationHelper.java:110)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at java.util.HashMap.readObject(HashMap.java:1404)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.pac4j.core.util.JavaSerializationHelper.unserializeFromBytes(JavaSerializationHelper.java:72)
	at org.pac4j.core.util.JavaSerializationHelper.unserializeFromBase64(JavaSerializationHelper.java:59)
	at org.pac4j.play.PlayWebContext.getRequestAttribute(PlayWebContext.java:206)
	at org.pac4j.core.profile.ProfileManager.retrieveAll(ProfileManager.java:58)
	at org.pac4j.core.profile.ProfileManager.get(ProfileManager.java:35)
```


Notes:

- I do not use `SecurityFilter`
- I use Play 2.5.9 with Scala
- I do not know why there is wrong class loader
- IMHO using flashscope and serialization to pass data between filter and the action is ugly solution. 1) flash scope is not inteded for it and it is much bigger scope, 2) you store unnecessarily big data into the response and the subsequent request, 3) serialization and deserialization of the data within a single request is unneccessary overhead slowing the application. Considering Play is intended for high load, this is definitely wrong approach.

**Comment by leleuj** [comment]
I agree: minor versions should not have breaking changes (whether at runtime or compilation). But I was in a hurry to release pac4j v1.9.4 which fixes a security issue and then play-pac4j v2.5.1. It was mostly bad luck, but we can do better. In fact, I didn't expect so many troubles.

I guess you suffer from this exception: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/util/JavaSerializationHelper.java#L113 In fact, you can control the classes which are authorized to be serialized via: `PlayWebContext.JAVA_SERIALIZATION_HELPER.getTrustedPackages().add`.

Previously, I was using the Java context, built from the Scala tags of the request. No serialization indeed, but it really feels like a hack. I changed it when making it work with the `SecurityFilter`, it felt more consistent, but the serialization is a major downside for performance. I'll change that: https://github.com/pac4j/play-pac4j/issues/156

**Comment by KarelCemus** [comment]
Ad the exception: You are right, but that is what I mention here:

> Third, since bugfix release you introduce trustedPackages in JavaSerializationHelper and reject untrusted classes. Personally, I see that as a bad practice because it requires migration, i.e., not bugfixing release

When I added that package into trusted packages, I the program goes into https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/util/JavaSerializationHelper.java#L110 and fails with ClassNotFoundException again. Please see the call stack, it is visible there.

And regarding the hacks.... you should consider not using the flashing scope. The warning by Play should be the hint not to do that itself among other reasons.

**Comment by leleuj** [comment]
I reverted to using the args instead of the flash scope for the "request attributes". It should solve your problem. Can you confirm everything is ok with version 2.5.2-SNAPSHOT?

I'll take a look at your issue separately.

**Comment by KarelCemus** [comment]
I tried 2.5.2-SNAPSHOT and it seems OK. Logs are clean and everything works but I tested it only briefly.

Thanks!

**Comment by leleuj** [comment]
Thanks. I will do more tests to ensure everything is ok for a 2.5.2.

**Comment by gpgekko** [comment]
As a note: in the upcoming Play 2.6, the [old tags field is replaced with an attributes field](https://www.playframework.com/documentation/2.6.x/Migration26#Request-attributes), which accepts objects instead of just strings. Perhaps it can be useful to this case, since the tags were considered but not used due to its string only limitation.

**Comment by leleuj** [comment]
Thanks for the information. Indeed, we have had troubles handling request attributes properly.

I tracked that here: https://github.com/pac4j/play-pac4j/issues/173

**Comment by richard77** [comment]
Cool! That solves many issues we had with the Filter implementation.
Thanks for the heads-up.
Op do 16 feb. 2017 om 14:53 schreef LELEU Jérôme <notifications@github.com>
