### ISSUE TITLE
logout not working as expected 

### ISSUE THREAD

**Issue by kedall** [pac4j/play-pac4j#153]
Hi, 
I am trying the demo play app and the session is still valid even after i click the logout url - i did not change the default implementation:

```
>         // logout
>         final ApplicationLogoutController logoutController = new ApplicationLogoutController();
>         logoutController.setDefaultUrl("/?defaulturlafterlogout");
>         bind(ApplicationLogoutController.class).toInstance(logoutController);
```

How does one logout ?

**Comment by leleuj** [comment]
Very strange! I test it regularly and it works. The application session is destroyed. Notice the identity server session is not destroyed (this is planned for version 2).
Use the mailing list for questions.

**Comment by kedall** [comment]
hi, 
 im not sure what you consider working - but to me - if i logout - i expect to be asked to login again to visit a protected page.

https://vid.me/QuTj

if i run the code - it does not look like it does that - it thinks im logged in even after I click logout.

**Comment by millross** [comment]
Your browser is caching the basic auth credentials and is resubmitting the relevant header - see https://en.wikipedia.org/wiki/Basic_access_authentication . They all do it. Use the browser dev tools to examine the requests as you submit them and you’ll see it happen. That’s not a bug in pac4j, it’s because there’s no formal mechanism for telling the browser to discard the credentials following logout. It would be nice if there were, but basic auth. If you use something like curl to submit 3 requests (one for initial login and access to protected resource, with basic auth header, one for logout, and one for protected resource, without basic auth header) you’ll see a different behaviour.

**Comment by millross** [comment]
Your browser is caching the basic auth credentials and is resubmitting the relevant header - see https://en.wikipedia.org/wiki/Basic_access_authentication <https://en.wikipedia.org/wiki/Basic_access_authentication> . They all do it. Use the browser dev tools to examine the requests as you submit them and you’ll see it happen. That’s not a bug in pac4j, it’s because there’s no formal mechanism for telling the browser to discard the credentials following logout. It would be nice if there were, but basic auth. If you use something like curl to submit 3 requests (one for initial login and access to protected resource, with basic auth header, one for logout, and one for protected resource, without basic auth header) you’ll see a different behaviour.
