### ISSUE TITLE
Client, that not present into "clients" list, has ability to call method

### ISSUE THREAD

**Issue by ArkadyKarev** [pac4j/play-pac4j#168]
Hello!

I trying to implement attaching social network account to existing user profile. For this purpose I created endpoint and annotated it with
`@Secure(clients = "FacebookClient")`
It working smoothly for authentication when user not logged in. But when I authenticated with FormClient, I can call this method directly, and FacebookClient authenticator doesn't triggered, despite the fact that FormClient was not present in the 'clients' list.

Is It a bug?

I expected, that this approach will trigger Facebook auth, and profileManager.getAll() will return a list with 2 profiles, and then I could associate one account with another.

So if it is correct behavior, how can I force pac4j to trigger Facebook authentication when I already authenticated with another client?

I using 1.9.5 pac4j, and 2.4.0 play-pac4j versions

**Comment by leleuj** [comment]
No, this is the expected behaviour: the `clients` parameter says what authentication methods will be triggered if the user is **not** authenticated. So if you are already authenticated by a `FormClient`, you can access a URL protected by another client.

To trigger a Facebook authentication in addition to the form login page one, you need to call it explicitly.
See the demos: https://github.com/pac4j/play-pac4j-java-demo and https://github.com/pac4j/play-pac4j-scala-demo
Especially: https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/controllers/Application.java#L152 and https://github.com/pac4j/play-pac4j-scala-demo/blob/master/app/controllers/Application.scala#L146

Despite the multi-profiles handling (added recently), this behaviour has remained consistent since pac4j v1.0.
