### ISSUE TITLE
Upgrading to Play 2.6

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#173]
and especially getting rid of the tags mechanism in favor of the new attributes one.

**Comment by taggiasco** [comment]
Hello,
I pulled the master and created a new branch for Play 2.6 (upgrade-play-2.6).
I changed Play version (2.6.0-M5 for the moment) and added Google Guice as a dependency.
The tests do not pass yet. There is a problem with the injection, it looks a class is not found (which is normal because it was deprecated in PLay 2.5 and has disappeared from Play 2.6).
However, are you interested in a PR ? If so, in which branch ?
Best regards,
Matt

**Comment by leleuj** [comment]
Yes, I'm really interested in the upgrade to Play 2.6, but I'm sure the Play community is a lot more ;-)

For now, the master is on 3.0.1-SNAPSHOT, but I plan to create a 3.0.x branch and upgrade the master to 4.0.0-SNAPSHOT when it is appropriate. So your PR must be opened for the master branch (and you should update it to 4.0.0-SNAPSHOT). You'll also need to submit PR for the demos: 
https://github.com/pac4j/play-pac4j-java-demo and https://github.com/pac4j/play-pac4j-scala-demo in the same way.

Thanks for your help.
