### ISSUE TITLE
Blocking in default thread pool

### ISSUE THREAD

**Issue by gmethvin** [pac4j/play-pac4j#182]
I noticed a problem in your `SecureAction`: https://github.com/pac4j/play-pac4j/blob/master/src/main/java/org/pac4j/play/java/SecureAction.java#L106

it looks like you're calling `CompleteableFuture#get` within a thread executing on the default execution context (`HttpExecutionContext` by default is bound to the default thread pool, normally configured for CPU-bound operations). This can easily lead to thread starvation and poor performance.

Basically, it's a very bad idea to call `get` on a `CompleteableFuture` in production code. It really should be possible to rewrite the authentication code to avoid calling `get`, but I'm not familiar enough with pac4j to provide any specific suggestions.

I also noticed `SessionStore` is a blocking implementation, which could be a problem if it happens to do expensive I/O. Using a fast cache probably helps, but it would be ideal if the API were async.

I don't feel pac4j is an acceptable auth solution for Play unless it can do async properly, especially if it blocks on arbitrary user code.

**Comment by leleuj** [comment]
At a general level, pac4j is primarily a blocking library as we target many many frameworks, but indeed, it may be an issue like the SessionStore. One of the pac4j committer (the maintainer for Vert.x) is working on that, but it will take time: https://github.com/pac4j/pac4j/issues/180

Regarding the implementation in SecureAction, we rely on the pac4j core `SecurityLogic` which calls the `SecurityGrantedAccessAdapter` component in case of successful authentication, but indeed, calling `CompleteableFuture#get` does not seem like the best idea. What do you propose?

**Comment by millross** [comment]
Quite importantly, SessionStore being blocking is likely to be small potatoes compared with blocking clients (many of which will make blocking http calls to remote servers as part of the authentication process). There wouldn't be much point in making SessionStore alone non-blocking and async, because in the end the pac4j API is fundamentally synchronous, which means blocking a thread somewhere down the line to wait for a pipeline of async operations to complete.

Hence, as Jérôme points out, it will take some time to get to a fully async version of the core API (and we will need to build a strategy over time for building non-blocking client implementations from the async interfaces), but there is work under way, and it has been progressing. If you'd like to look over the pac4j-async work to date, feel free to make contributions as PRs, or raise new issues in areas not yet covered, all input would be welcome.

@leleuj , there are some core API changes I'd line up for 3.0 to ease exposure of an async API and enable code reuse between e.g. sync and async WebContext classes (and any code which consumes them). I will start raising some issues in the near future for consideration, but one of them touches very close to this SessionStore issue.

**Comment by leleuj** [comment]
@millross : No problem

@gmethvin : pac4j-async: https://github.com/millross/pac4j-async

**Comment by gmethvin** [comment]
@leleuj I don't understand the API well enough to know the best solution. You need to return immediately from the authentication action and then handle the action asynchronously. I think that's what you're doing here: https://github.com/pac4j/play-pac4j/blob/master/src/main/scala/org/pac4j/play/filters/SecurityFilter.scala#L89

Also, this should definitely be labeled as a bug.

**Comment by leleuj** [comment]
@taggiasco Matthieu, any idea on this?

**Comment by taggiasco** [comment]
@leleuj Hi ! I'm sorry, I didn't notice you were asking me.
I can see the mentioned problem with the get() call on a completable future and I understand it. But if you change it, you need to change the SecurityLogic too in order to use a CompletableFuture instead of a simple SecurityGrantedAccessAdapter. Doesn't seem to a backward compatible change, is it ?
@gmethvin I don't think it's a bug, because everything is working now. It's an improvement.

**Comment by leleuj** [comment]
@taggiasco In fact, the `SecurityGrantedAccessAdapter` can return anything as it's parametrized. It may be not backward compatible, but as we work on 4.0, it can be the right time to change that (if it is possible).

**Comment by taggiasco** [comment]
@leleuj then why not give it a try

**Comment by leleuj** [comment]
Sure, waiting for your PR ;-)

**Comment by gmethvin** [comment]
@taggiasco This is a bug in that it causes a significant performance degradation. It will be especially problematic with a large number of simultaneous requests, since each one blocks a thread.

**Comment by taggiasco** [comment]
@gmethvin I understand. From that point of view, I agree with you.

**Comment by millross** [comment]
Unfortunately there's a wider problem here for async frameworks such as play: all i/o in pac4j is fundamentally blocking at present. Any http calls for example also block. The CompletableFuture.get mentioned above is the tip of a rather large iceberg. Working on pac4j-async is showing me just how tightly coupled to blocking i/o the current pac4j API currently is. Fixing the CompletableFuture.get will just expose a performance degradation in other areas (esp with indirect clients which make http calls, or with any authorization/authentication which uses JDBC).

Frankly, the best approach for play in the near term would be to do similar to the vertx implementation and move the whole call into security/callback/logout logic off the main thread pool and deal with the result asynchronously.

**Comment by gmethvin** [comment]
The main problem here is that you're blocking on arbitrary user code. That for me is what makes it a bug rather than a feature request. If you had only the actual authentication operations happening in a separate thread pool from the main Play thread pool, then at least you're limiting the scope of the blocking to the pac4j stuff. As it is now you don't really know what you're blocking on.

**Comment by leleuj** [comment]
Any proposal on this?

**Comment by taggiasco** [comment]
@leleuj Did not find any time for this...

**Comment by leleuj** [comment]
@gmethvin @taggiasco What do you think of https://github.com/pac4j/play-pac4j/pull/194?
