### ISSUE TITLE
Play 2.6.6 EhCache with disk persistence

### ISSUE THREAD

**Issue by joantune** [pac4j/play-pac4j#205]
@leleuj the issues that made you write that line on the `Readme.md` about not using play 2.6.3 are related with this:
https://github.com/playframework/playframework/issues/7953

I would suggest that we do something like:

https://github.com/playframework/playframework/issues/6207#issuecomment-237003022

when using Cache - I might offer a PR soon WDYT?

**Comment by joantune** [comment]
This issue is also solved by doing what is stated here:

https://www.playframework.com/documentation/2.6.x/JavaCache#Setting-the-execution-context

i.e.  adding this:

```
play.cache.dispatcher = "contexts.blockingCacheDispatcher"

contexts {
  blockingCacheDispatcher {
    fork-join-executor {
      parallelism-factor = 3.0
    }
  }
}
```

to the config

**Comment by leleuj** [comment]
Both versions (2.6.3 and 2.6.5) have different issues.

What you propose fixes the error of the `TimeoutException` which happens in version 2.6.3.

But in the version 2.6.5, there was a bug on the time unit, which forces developers to reset the timeout: `playCacheSessionStore.setTimeout(3600000);` as it's in milliseconds instead of seconds.

So I have no problem to change the documentation to replace the "Do not use" by "Be careful, if you use this version, you must do that".

Would you mind submitting a pull request for that? Thanks

**Comment by leleuj** [comment]
Closing. Feel free to reopen with a contribution.
