### ISSUE TITLE
Support for Play 2.7

### ISSUE THREAD

**Issue by eximius313** [pac4j/play-pac4j#239]
Do you have any plans to support Play 2.7 (currently `2.7.0-M2`)?

**Comment by leleuj** [comment]
Sure. It will be for the new version 7 of play-pac4j.

**Comment by gpgekko** [comment]
Took a quick glance at the migration document of Play, and at first sight I think these are the things to do:

- [ ] [SecurityFilter.scala](https://github.com/pac4j/play-pac4j/blob/e2b74f352aa31d035163f484a996c9fe8ac74416/shared/src/main/scala/org/pac4j/play/filters/SecurityFilter.scala#L13) uses the deprecated [`play.Logger`](https://www.playframework.com/documentation/2.7.0-RC3/Migration27#play.Logger-deprecated). This seems like an inconsistency anyway, since the rest of the code already uses the `org.slf4j.Logger`
- [ ] The `get` method on the `cacheApi` has been deprecated [in favour of `getOptional`](https://www.playframework.com/documentation/2.7.0-RC3/Migration27#The-Java-Cache-API-get-method-has-been-deprecated-in-favor-of-getOptional). This has implications for the `PlayCacheStore`.
- [ ] The Java API has had a big overhaul, [deprecating the `play.mvc.Http.Context` class](https://www.playframework.com/documentation/2.7.0-RC3/JavaHttpContextMigration27)
  - [ ] PlayWebContext will need to be based on the `play.mvc.Request`, allowing access to the request and the session.
  - [ ] PlayWebContext will no longer have [access to the `play.mvc.Response`](https://www.playframework.com/documentation/2.7.0-RC3/JavaHttpContextMigration27#Http.Context.response()-and-Http.Response-class-deprecated), which will need a bit of reworking
  - [ ] The `LogoutController` and `CallbackController` will need to [have the `play.mvc.Request` passed in](https://www.playframework.com/documentation/2.7.0-RC3/JavaHttpContextMigration27#Http.Context.current()-and-Http.Context.request()-deprecated)
  - [ ] Actions are no longer [based on context, but on request](https://www.playframework.com/documentation/2.7.0-RC3/JavaHttpContextMigration27#Action.call(Context)-deprecated), so the [`SecureAction`](https://github.com/pac4j/play-pac4j/blob/master/shared/src/main/java/org/pac4j/play/java/SecureAction.java#L79) will need to be changed

This probably all has implications for the Deadbolt parts, but I didn't look through those (Deadbolt itself first needs to be updated).

**Comment by leleuj** [comment]
Thanks for the feedback @gpgekko. We are still working on play-pac4j v7 based on pac4j v3.4 and Play 2.6, but you can maybe open a PR to accommodate the changes (this will go into play-pac4j v8).

**Comment by eximius313** [comment]
https://github.com/schaloner/deadbolt-2-java/pull/95

**Comment by mellster2012** [comment]
PR for those who want to upgrade before the refactoring: https://github.com/pac4j/play-pac4j/pull/261

**Comment by eximius313** [comment]
Deadbolt for 2.7 is released now: https://github.com/schaloner/deadbolt-2-java/releases/tag/v2.7.0

**Comment by ndimas** [comment]
Hello @leleuj , do you need any help with this task?

**Comment by leleuj** [comment]
Sure. This change needs to be fully tested and the Deadbolt dependency should be updated in version 2.7 if I'm not mistaken...

**Comment by vidma** [comment]
I tested it a bit with play 2.7. seems to work fine so far with ldap & saml.

@leleuj any plans to release 8.0.0 with play 2.7 support soon? or do we need to release our own fork for the time being?

**Comment by leleuj** [comment]
I'm working on it...

**Comment by leleuj** [comment]
The release v8.0.0 is now available in the Maven central repository.

**Comment by gpgekko** [comment]
Note that this might be done in the sense that the version is bumped and it runs, but my list above still applies: a lot of things that are used by this project (and the imported version of Deadbolt) are deprecated and will be removed in the next Play version. I'll open a new issue to track that work.

**Comment by leleuj** [comment]
I re-opened the issue for the remaining work... It can be a version 8.1 or 9.0...

**Comment by ijaxahmed** [comment]
is 8.0.0  supporting play 2.7 and available in IVY dependency manager ? 
if not, then it means pac4j cant be used with play2.7 when using sbt ?

**Comment by ijaxahmed** [comment]
> The release v8.0.0 is now available in the Maven central repository.

is it also available in IVY dependency manager ? right now if i mention in sbt dependency , got error like 

org.pac4j#play-pac4j;8.0.0: not found

**Comment by leleuj** [comment]
Strange, isn't Maven central repository a default repo of the build.sbt file?

**Comment by ijaxahmed** [comment]
> Strange, isn't Maven central repository a default repo of the build.sbt file?

sbt uses Apache Ivy to implement managed dependencies
https://www.scala-sbt.org/release/docs/Library-Dependencies.html

**Comment by taggiasco** [comment]
Hi @ijaxahmed 
I had the same problem. I used to reference the library as :
`"org.pac4j" % "play-pac4j" % "8.0.0"`
but it wasn't enough and I had to explicitly add the Scala version :
`"org.pac4j" % "play-pac4j_2.12" % "8.0.0"`
I don't know the reason, because at the same time, I upgraded to SBT 1.x, so it might be because of the update, or something else.

**Comment by leleuj** [comment]
`play-pac4j` does not exist in version 8.0.0, it used to be the parent pom, now it's `play-pac4j-parent` to avoid any confusion.
Use: `play-pac4j_2.11` or `play-pac4j_2.12`

**Comment by ijaxahmed** [comment]
Thank you @taggiasco and @leleuj

**Comment by petahathub** [comment]
Hi,
now Play Framework 2.8 is out. How about support for 2.7 and it's breaking changes in Http.Context?

I shall be most gratefull if you could move a little forward this awesome play-pac4j!

**Comment by leleuj** [comment]
I have that in mind. My main goal currently is to upgrade to pac4j v4. But I know there are the waiting supports for Play 2.7 and Play 2.8 and Scala 2.13. I think the best option is to move to pac4j v4 first (play-pac4j v9), but I'm open to suggestions...

**Comment by SoerenSilkjaer** [comment]
I made a pr that upgrades this project to pac4j v4 https://github.com/pac4j/play-pac4j/pull/267 
Hope it helps in the upgrade process.

**Comment by leleuj** [comment]
The complete upgrade to Play v2.7 has been done:
- `Optional` in the `PlayCacheStore`
- removal of the `Http.Context` in favor of the `Http.RequestHeader`.
