### ISSUE TITLE
how to unit test controller annotated with RequiersAuthentication

### ISSUE THREAD

**Issue by eagelberg** [pac4j/play-pac4j#55]
hi,
i'm using play-pac4j with play framework 2.3 and i want to write unit test for my controller using the fakeRequest of play. but in the fake request he cant connect to my cas server.
Is there a way around this?

**Comment by leleuj** [comment]
The core behaviour of `pac4j` is to send the user to a CAS server (or whatever identity provider you use) and authenticates him with the returned credentials. If you want to simulate this part, the best way is to create your own implementation of https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/Client.java with the expected behaviour.
