### ISSUE TITLE
Persisting sessions?

### ISSUE THREAD

**Issue by princegoyal1987** [pac4j/play-pac4j#71]
Is there a way to persist sesions. Each play reload (or small code change) logs out. Any solution?

**Comment by leleuj** [comment]
"Session" is a bit misleading, because in fact, only an identifier is stored into the Play session (in the cookie) while all data are managed into the Cache.

So I think the problem comes from the Cache here as the cookie certainly stays unchanged. As the default Cache is in memory, things are lost. You may want to try an external Cache (in Memcached or Redis) or wait for the version 2.0 ;-)

**Comment by princegoyal1987** [comment]
Got it! I will use redis the. 

Thanks for the quick reply :)

**Comment by leleuj** [comment]
There is now an obvious `CacheStore` to store data and I'm pretty sure it would be easy to create a `SessionStore` if you need one.

See: https://github.com/pac4j/play-pac4j/blob/master/play-pac4j-java/src/main/java/org/pac4j/play/store/CacheStore.java
