### ISSUE TITLE
Complete JWT Example

### ISSUE THREAD

**Issue by cmoro-deusto** [pac4j/play-pac4j#84]
Hi there!

   first of all, thank you very much for creating pac4j. It’s an awesome piece of work.

I’m trying to integrate pac4j in a play 2.4 application, in order to implement JWT based authentication.

I have downloaded and studied the play-pac4j-java-demo application but I couldn’t make the JWT auth to work:

 - Login using theform or basic auth.
 - Login works and a UserProfile is instantiated and show on the index view.
 - Go to the jwt.html view and get the token generated.
 - After all of that, I try to load a protected view, but I always get a 401 error if I try to use the JWT in a HTTP header. It works if I use the ParameterClient with the token URL Param.

Could you please advise on how to actually proceed with JWT authentication implementation using the token in a HTTP Header? I have searched the groups and googled around for hours but couldn’t find any example.

Thank you very much in advance.

**Comment by leleuj** [comment]
By default, the Play demos expect the token to be passed via a request parameter (that's why a `ParameterClient` is used). If you want to pass the token as a header, you need to instantiate a `HeaderClient` instead of the `ParameterClient`: https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/direct/HeaderClient.java

All clients are listed here: https://github.com/pac4j/pac4j/wiki/Clients

**Comment by cmoro-deusto** [comment]
OK, that's what I thought, I was confused by the index option "Protected url by DirectBasicAuthClient (POST the Authorization header with value)", which fails.

Thanks very much.
